openapi: 3.0.0
info:
  title: FormSchemaProvider API
  version: "1.0"
paths:
  /api/cards/visible:
    get:
      summary: Get all visible cards for the authenticated user
      operationId: getVisibleCardsForCurrentUser
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FormSchema'
      security:
        - bearerAuth: []
components:
  schemas:
    FormSchema:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
        type:
          type: string
          enum:
            - form
            - card
        showCardOnUi:
          type: boolean
        roles:
          type: array
          items:
            type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
